# NUMEROS ENTEROS INT
10
print(type(5))
# TIPO FLOAT
10.54
print(type(10.54))


# OPERACIONES MATEMATICAS
1+1 # SUMA
print(1+1)

2-1 # RESTA
print(2-1)

2*4 # MULTIPLICACION
print(2*4)

6/2 # DIVICION
print(6/2)

2**3 # ELEVAR AL CUBO
print(2**3)

3//2 # OPERADOR DE MODULO SOLO DEVUELVE EL RESIDUO
print(3//2)
10%3 # OPERADOR DE MODULO SOLO DEVUELVE EL RESIDUO
print(10%3 )

#OPERACIONES EXPODENCIALES

3+2, 1-2, 3*4, 2**3
print(3+2, 1-2, 3*4, 2**3)


# FUNCION PARA PEDIR LA EDAD EJEMPLO EN N FORMULARIO

age = input("Inserte su Edad:") # GUERDO EN UNA VARIABLE A LO QUE INGRESE LA EDAD
newAge = int(age) + 5 # QUIERO SUMARLE + 5 ADEMAS QUERO GRABARLO EN OTRA VARIABLE ADEMAS LO CONVIERTO
print (newAge)

